"""BuildPlan — generated by the Resolver, consumed (in future) by the Builder.

Phase 2 does NOT execute BuildPlan.  It only generates and validates it.
"""

from __future__ import annotations

from dataclasses import dataclass, field
from qsys.feature.resolver_v2 import ResolvedFeatureSet


@dataclass(frozen=True)
class FeatureBuildPlan:
    """The build plan for a resolved FeatureSet.

    Phase 2: only generated and validated, not executed.
    Phase 4+: consumed by builder to drive actual feature computation.
    """

    feature_set_id: str
    final_features: tuple[str, ...]

    required_raw_features: tuple[str, ...]
    required_derived_features: tuple[str, ...]
    required_transforms: tuple[str, ...]
    unresolved_transforms: tuple[str, ...]

    warnings: tuple[str, ...]


def build_plan_from_resolved(resolved: ResolvedFeatureSet) -> FeatureBuildPlan:
    """Generate a ``FeatureBuildPlan`` from a ``ResolvedFeatureSet``.

    This is a pure validation step — it does NOT execute any transforms.

    Rules:
    1. ``resolved_features`` must not be empty.
    2. If a derived feature has no ``compute_fn`` mapping in the resolver
       result, it goes into ``unresolved_transforms`` with a warning.
    3. ``required_transforms`` = sorted set of all ``compute_fn`` values
       found across resolved features.
    4. ``unresolved_transforms`` = derived features whose compute_fn is empty.
    """
    if not resolved.resolved_features:
        raise ValueError(
            f"Cannot build plan for '{resolved.feature_set_id}': "
            f"resolved_features is empty"
        )

    transforms: set[str] = set()
    unresolved: list[str] = []

    for info in resolved.spec_sources:
        fn = info.get("compute_fn", "")
        if info["kind"] == "derived":
            if fn:
                transforms.add(fn)
            else:
                unresolved.append(info["name"])

    return FeatureBuildPlan(
        feature_set_id=resolved.feature_set_id,
        final_features=resolved.resolved_features,
        required_raw_features=resolved.raw_features,
        required_derived_features=resolved.derived_features,
        required_transforms=tuple(sorted(transforms)),
        unresolved_transforms=tuple(unresolved),
        warnings=resolved.warnings,  # warnings come from resolver only
    )
